import { $, toast, I, pushHist, after, saveProject, loadProjectObj } from '../state.js';
import { startSched, stopSched } from '../scheduler.js';
import { clamp, GROOVES, loopLen } from '../model.js';
import { renderBounce, stemTracks, wavEncode, pcmFromBuffer } from '../bounce.js';
import { encodeShare } from '../share.js';

function renderHeader(){if($('grooveSel').options.length===0)$('grooveSel').innerHTML=Object.keys(GROOVES).map(k=>'<option value="'+k+'">'+GROOVES[k].label+'</option>').join('');$('grooveSel').value=I.p.groove||'straight';if(document.activeElement!==$('seedIn'))$('seedIn').value=I.p.seed||'PSY6';$('fsm').textContent=I.fsm;$('bpm').value=I.p.bpm;$('swing').value=I.p.swing;$('swV').textContent=I.p.swing+'%';$('bPlay').classList.toggle('on',['PLAYING','RECORDING','TRANSITIONING'].includes(I.fsm));$('bRec').classList.toggle('on',I.recOn);$('bChain').classList.toggle('on',I.p.chain);$('bChain').textContent='CHAIN '+(I.p.chain?'ON':'OFF')}

function wireHeader(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('on'));$('tab-'+b.dataset.t).classList.add('on')});$('bPlay').onclick=()=>{if(I.fsm==='OFF')return;if(['PLAYING','RECORDING','TRANSITIONING'].includes(I.fsm))return;I.fsm=I.recOn?'RECORDING':'PLAYING';startSched();renderHeader()};$('bStop').onclick=()=>{if(['PLAYING','RECORDING','TRANSITIONING'].includes(I.fsm)){stopSched();I.fsm='READY';I.pending=null;renderHeader()}};$('bRec').onclick=()=>{I.recOn=!I.recOn;if(I.recOn&&I.fsm==='READY'){I.fsm='RECORDING';startSched()}else if(I.fsm==='PLAYING'||I.fsm==='RECORDING')I.fsm=I.recOn?'RECORDING':'PLAYING';renderHeader()};$('bPanic').onclick=()=>{if(I.eng)I.eng.killAll();toast('PANIC — all voices killed')};$('bpm').onchange=e=>{pushHist();I.p.bpm=clamp(+e.target.value,40,300);after()};$('swing').oninput=e=>{$('swV').textContent=e.target.value+'%'};$('swing').onchange=e=>{pushHist();I.p.swing=clamp(+e.target.value,0,66);after()};$('grooveSel').innerHTML=Object.keys(GROOVES).map(k=>'<option value="'+k+'">'+GROOVES[k].label+'</option>').join('');$('grooveSel').onchange=e=>{pushHist();I.p.groove=e.target.value;I.renderDirty=true};$('seedIn').onchange=e=>{pushHist();I.p.seed=e.target.value.trim()||'PSY6';I.renderDirty=true};$('bUndo').onclick=()=>{if(I.hist.length){I.redo.push(JSON.stringify(I.p));I.p=JSON.parse(I.hist.pop());I.dirty=true;I.renderDirty=true}};$('bRedo').onclick=()=>{if(I.redo.length){I.hist.push(JSON.stringify(I.p));I.p=JSON.parse(I.redo.pop());I.dirty=true;I.renderDirty=true}};$('bSave').onclick=()=>{const r=saveProject();toast(r.ok?'SAVED ✓':'SAVE FAILED')};$('bShare').onclick=async()=>{if(!I.p)return;if(I.copilotSnapshot)I.copilotSnapshot();const r=await encodeShare(I.p);
if(!r.ok&&r.reason==='no-compression'){toast('SHARE: this browser lacks CompressionStream — use EXPORT instead (no quality loss)');return}
if(!r.ok){toast('SHARE FAILED — link too large ('+((r.tokenBytes||0)/1024|0)+' KB) — use EXPORT');return}
location.hash='p='+r.token;const url=location.origin+location.pathname+'#p='+r.token;
try{await navigator.clipboard.writeText(url);toast('SHARE LINK copied ✓ '+(r.tokenBytes/1024|0)+' KB'+(r.warn?' — large, may exceed some URL limits':''))}catch(e){toast('SHARE LINK in the address bar ('+(r.tokenBytes/1024|0)+' KB) — copy it there')}};$('bExport').onclick=()=>{if(I.copilotSnapshot)I.copilotSnapshot();const blob=new Blob([JSON.stringify(I.p)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='psy6-project.json';a.click()};$('bImport').onclick=()=>$('impF').click();$('impF').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const p=JSON.parse(rd.result);if(p&&p.version===3&&p.tracks){loadProjectObj(p);toast('imported')}else toast('invalid file')}catch(err){toast('IMPORT FAILED')}};rd.readAsText(f)};$('bChain').onclick=()=>{I.p.chain=!I.p.chain;renderHeader()};
/* ── BOUNCE — offline WAV render (never touches the live AudioContext) ── */
$('bBounce').onclick=()=>{if(!I.p)return;$('bounceModal').style.display='flex';bounceInfo()};
const dlWav=(ab,name)=>{const blob=new Blob([ab],{type:'audio/wav'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)};
const bounceInfo=()=>{const loops=+$('bounceLoops').value;const L=loopLen(I.p);const dur=.05+L*loops*60/I.p.bpm/4;const mode=$('bounceMode')?$('bounceMode').value:'mix';if(mode==='stems'){const n=stemTracks(I.p,loops).tracks.length;$('bounceInfo').textContent=I.p.bpm+' BPM · loop '+L+' steps · '+n+' non-empty track'+(n===1?'':'s')}else{$('bounceInfo').textContent=I.p.bpm+' BPM · loop '+L+' steps · '+dur.toFixed(2)+'s · '+Math.ceil(dur*44100)+' samples'}};
$('bounceLoops').onchange=bounceInfo;if($('bounceMode'))$('bounceMode').onchange=bounceInfo;
$('bounceCancel').onclick=()=>{$('bounceModal').style.display='none';$('bounceGo').disabled=false;$('bounceGo').textContent='RENDER WAV'};
$('bounceGo').onclick=async()=>{const b=$('bounceGo');b.disabled=true;b.textContent='RENDERING…';try{const loops=+$('bounceLoops').value;const mode=$('bounceMode')?$('bounceMode').value:'mix';
if(mode==='stems'){const {tracks}=stemTracks(I.p,loops);if(!tracks.length){toast('STEMS: no notes in this pattern');b.disabled=false;b.textContent='RENDER WAV';return}
let done=0;for(const ti of tracks){const {buf,N}=await renderBounce(I.p,loops,{trackIdx:ti});const pcm=pcmFromBuffer(buf);const ab=wavEncode(pcm.channels,pcm.sampleRate);const nm=(I.p.tracks[ti].name||('track-'+ti)).replace(/\s+/g,'-').toLowerCase();dlWav(ab,'psy6-stem-'+nm+'.wav');done++;await new Promise(r=>setTimeout(r,350))/* sequential downloads — browsers throttle rapid clicks */}
toast('STEMS ✓ '+done+' file'+(done===1?'':'s')+' · '+N+' samples each');$('bounceModal').style.display='none'}
else{const {buf,N}=await renderBounce(I.p,loops);const pcm=pcmFromBuffer(buf);const ab=wavEncode(pcm.channels,pcm.sampleRate);dlWav(ab,'psy6-bounce-'+I.p.bpm+'bpm.wav');toast('BOUNCED ✓ '+N+' samples · '+(ab.byteLength/1024|0)+' KB');$('bounceModal').style.display='none'}}catch(err){toast('BOUNCE FAILED — '+err.message)}b.disabled=false;b.textContent='RENDER WAV'};
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;if(e.code==='Space'){e.preventDefault();if(['PLAYING','RECORDING','TRANSITIONING'].includes(I.fsm))$('bStop').click();else $('bPlay').click()}else if(e.key==='r')$('bRec').click();else if(e.key==='z'){if(e.shiftKey)$('bRedo').click();else $('bUndo').click()}else if(e.key>='1'&&e.key<='8'){I.selTrack=+e.key-1;I.renderDirty=true}})}

export { renderHeader, wireHeader };
