import { $, toast, I, pushHist, after, saveProject, loadProjectObj } from '../state.js';
import { startSched, stopSched } from '../scheduler.js';
import { clamp, GROOVES } from '../model.js';

function renderHeader(){if($('grooveSel').options.length===0)$('grooveSel').innerHTML=Object.keys(GROOVES).map(k=>'<option value="'+k+'">'+GROOVES[k].label+'</option>').join('');$('grooveSel').value=I.p.groove||'straight';if(document.activeElement!==$('seedIn'))$('seedIn').value=I.p.seed||'PSY6';$('fsm').textContent=I.fsm;$('bpm').value=I.p.bpm;$('swing').value=I.p.swing;$('swV').textContent=I.p.swing+'%';$('bPlay').classList.toggle('on',['PLAYING','RECORDING','TRANSITIONING'].includes(I.fsm));$('bRec').classList.toggle('on',I.recOn);$('bChain').classList.toggle('on',I.p.chain);$('bChain').textContent='CHAIN '+(I.p.chain?'ON':'OFF')}

function wireHeader(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('on'));$('tab-'+b.dataset.t).classList.add('on')});$('bPlay').onclick=()=>{if(I.fsm==='OFF')return;if(['PLAYING','RECORDING','TRANSITIONING'].includes(I.fsm))return;I.fsm=I.recOn?'RECORDING':'PLAYING';startSched();renderHeader()};$('bStop').onclick=()=>{if(['PLAYING','RECORDING','TRANSITIONING'].includes(I.fsm)){stopSched();I.fsm='READY';I.pending=null;renderHeader()}};$('bRec').onclick=()=>{I.recOn=!I.recOn;if(I.recOn&&I.fsm==='READY'){I.fsm='RECORDING';startSched()}else if(I.fsm==='PLAYING'||I.fsm==='RECORDING')I.fsm=I.recOn?'RECORDING':'PLAYING';renderHeader()};$('bPanic').onclick=()=>{if(I.eng)I.eng.killAll();toast('PANIC — all voices killed')};$('bpm').onchange=e=>{pushHist();I.p.bpm=clamp(+e.target.value,40,300);after()};$('swing').oninput=e=>{$('swV').textContent=e.target.value+'%'};$('swing').onchange=e=>{pushHist();I.p.swing=clamp(+e.target.value,0,66);after()};$('grooveSel').innerHTML=Object.keys(GROOVES).map(k=>'<option value="'+k+'">'+GROOVES[k].label+'</option>').join('');$('grooveSel').onchange=e=>{pushHist();I.p.groove=e.target.value;I.renderDirty=true};$('seedIn').onchange=e=>{pushHist();I.p.seed=e.target.value.trim()||'PSY6';I.renderDirty=true};$('bUndo').onclick=()=>{if(I.hist.length){I.redo.push(JSON.stringify(I.p));I.p=JSON.parse(I.hist.pop());I.dirty=true;I.renderDirty=true}};$('bRedo').onclick=()=>{if(I.redo.length){I.hist.push(JSON.stringify(I.p));I.p=JSON.parse(I.redo.pop());I.dirty=true;I.renderDirty=true}};$('bSave').onclick=()=>{const r=saveProject();toast(r.ok?'SAVED ✓':'SAVE FAILED')};$('bExport').onclick=()=>{const blob=new Blob([JSON.stringify(I.p)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='psy6-project.json';a.click()};$('bImport').onclick=()=>$('impF').click();$('impF').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const p=JSON.parse(rd.result);if(p&&p.version===3&&p.tracks){loadProjectObj(p);toast('imported')}else toast('invalid file')}catch(err){toast('IMPORT FAILED')}};rd.readAsText(f)};$('bChain').onclick=()=>{I.p.chain=!I.p.chain;renderHeader()};window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;if(e.code==='Space'){e.preventDefault();if(['PLAYING','RECORDING','TRANSITIONING'].includes(I.fsm))$('bStop').click();else $('bPlay').click()}else if(e.key==='r')$('bRec').click();else if(e.key==='z'){if(e.shiftKey)$('bRedo').click();else $('bUndo').click()}else if(e.key>='1'&&e.key<='8'){I.selTrack=+e.key-1;I.renderDirty=true}})}

export { renderHeader, wireHeader };
