import { $, I, pushHist, after, PERF, recHit } from '../state.js';
import { SCALES, M_ENERGY, M_DRIVE, M_SPACE, M_MOVE } from '../model.js';

function renderScenes(){const w=$('scenes');w.innerHTML='';I.p.scenes.forEach((sc,i)=>{const b=document.createElement('button');b.className='scene'+(i===I.p.activeScene?' active':'')+(I.pending===i?' pending':'');const pn=sc.pattern!=null?(I.p.patterns[sc.pattern]?I.p.patterns[sc.pattern].name:'?'):'empty';b.innerHTML='<b style="font-size:11px">'+sc.name+'</b><div class="mono" style="font-size:8px;color:var(--dim)">'+pn+'</div>';b.onclick=e=>{if(e.shiftKey)PERF.assign(i);else PERF.launch(i,e.altKey)};w.appendChild(b)})}
function renderPads(){const pm=$('padModes');if(!pm.children.length)['DRUM','SCALE','CHORD'].forEach(m=>{const b=document.createElement('button');b.textContent=m;b.onclick=()=>{I.padMode=m;renderPads()};pm.appendChild(b)});[...pm.children].forEach(b=>b.classList.toggle('on',b.textContent===I.padMode));const g=$('pads');if(!g.children.length)for(let i=0;i<16;i++){const b=document.createElement('button');b.className='pad';b.addEventListener('pointerdown',e=>{e.preventDefault();padHit(i);b.classList.add('hit');setTimeout(()=>b.classList.remove('hit'),110)});g.appendChild(b)}[...g.children].forEach((b,i)=>{if(I.padMode==='DRUM'){const t=I.p.tracks[i%8];b.innerHTML='<span class="lb">'+(t?t.name.split(' ')[0]:'—')+'</span><span class="tg2">'+(t?t.kind:'')+'</span>'}else{b.innerHTML='<span class="lb">'+['I','II','III','IV','V','VI','VII','VIII'][i%8]+'</span><span class="tg2">'+(I.padMode==='CHORD'?'chord':'note')+'</span>'}})}
function padHit(i){const vel=(+$('padVel').value)/100;if(I.padMode==='DRUM'){const t=i%8;const tr=I.p.tracks[t];if(tr&&tr.kind==='drum'&&I.eng){I.eng.trigger(tr,I.ctx.currentTime,{vel,note:48,lock:{}},0);recHit(t,null,vel)}}else{const sc=SCALES[I.p.scale]||SCALES.minor;const deg=i;const idx=deg%sc.length,oct=Math.floor(deg/sc.length);const note=I.p.root+24+sc[idx]+12*oct;let ti=I.p.selTrack;if(I.p.tracks[ti].kind==='drum')ti=4;const tr=I.p.tracks[ti];if(I.padMode==='CHORD'){[0,2,4].forEach((k,j)=>{const dd=(idx+k)%sc.length,oo=Math.floor((idx+k)/sc.length);const n=I.p.root+24+sc[dd]+12*(oct+oo);I.eng.trigger(tr,I.ctx.currentTime,{vel:j===0?vel:vel*.75,note:n,lock:{}},0)});recHit(ti,note,vel)}else{I.eng.trigger(tr,I.ctx.currentTime,{vel,note,lock:{}},0);recHit(ti,note,vel)}}}
function renderTracks(){const w=$('tracks');w.innerHTML='';I.p.tracks.forEach((t,i)=>{const d=document.createElement('div');d.className='trk'+(i===I.selTrack?' sel':'');d.innerHTML='<span class="nm">'+t.name.split(' ')[0]+'</span><span class="ps">'+(t.presetId||'—')+'</span><div class="ms"><button class="mute'+(t.mix.mute?' on':'')+'">M</button><button class="solo'+(t.mix.solo?' on':'')+'">S</button></div><input type="range" min="0" max="100" value="'+Math.round(Math.sqrt(t.mix.vol)*100)+'" style="width:70px">';d.querySelector('.mute').onclick=e=>{e.stopPropagation();pushHist();t.mix.mute=!t.mix.mute;after()};d.querySelector('.solo').onclick=e=>{e.stopPropagation();pushHist();t.mix.solo=!t.mix.solo;after()};const rg=d.querySelector('input');rg.onclick=e=>e.stopPropagation();rg.oninput=e=>{t.mix.vol=Math.pow(+e.target.value/100,2);if(I.eng)I.eng.syncMix(I.p);I.dirty=true};d.onclick=()=>{I.selTrack=i;I.renderDirty=true};w.appendChild(d)})}
function renderLayers(){const w=$('layers');w.innerHTML='';[['drums','DRUMS'],['bass','BASS'],['music','MUSIC'],['fx','FX DELAY']].forEach(([k,lb])=>{const b=document.createElement('button');b.textContent=lb;b.style.padding='12px';const muted=k==='drums'?I.p.tracks.slice(0,4).every(t=>t.mix.mute):k==='bass'?I.p.tracks[4].mix.mute:k==='music'?I.p.tracks.slice(5,8).every(t=>t.mix.mute):I.p.tracks[4].mix.sendA===0;b.classList.toggle('on',muted);b.onclick=()=>PERF.toggleLayer(k);w.appendChild(b)})}
function renderMacros(){const w=$('macros');w.innerHTML='';[['ENERGY',M_ENERGY],['DRIVE',M_DRIVE],['SPACE',M_SPACE],['MOVEMENT',M_MOVE]].forEach(([nm,idx])=>{const d=document.createElement('div');d.className='macro';d.innerHTML='<span class="mn">'+nm+'</span><input type="range" min="0" max="100" value="'+Math.round(I.p.macroVals[idx]*100)+'">';d.querySelector('input').oninput=e=>PERF.macro(idx,+e.target.value/100);w.appendChild(d)})}

function wirePerform(){$('bFill').onclick=()=>PERF.fill();$('bVar').onclick=()=>PERF.variation();}

export { renderScenes, renderPads, renderTracks, renderLayers, renderMacros, wirePerform };
