import { $, I, pushHist, after } from '../state.js';
import { mkStep, clamp, deep } from '../model.js';

let gridCache={key:'',cells:[],len:0};

function renderPos(){const sc=I.sched;$('pos').textContent=sc.on?String(Math.floor(sc.step/16)+1).padStart(3,'0')+'.'+(Math.floor(sc.step%16/4)+1)+'.'+(sc.step%4+1):'—';if(gridCache.cells.length){const len=gridCache.len;const cur=sc.on?sc.step%len:-1;for(let i=0;i<gridCache.cells.length;i++)gridCache.cells[i].classList.toggle('play',i===cur)}}

function renderSeq(){const p=I.p,ti=I.selTrack,pat=p.patterns[p.currentPattern];if(!pat||!pat.data[ti])return;const d=pat.data[ti],len=d.len;$('seqT').textContent='Step Sequencer — '+p.tracks[ti].name+' · pattern '+pat.name+' · len '+len;const st=$('seqTrack');if(st.children.length!==p.tracks.length){st.innerHTML='';p.tracks.forEach((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=i+' '+t.name.split(' ')[0];st.appendChild(o)})}st.value=ti;const ls=$('lenSel');if(ls.children.length===0)[4,8,12,16,24,32].forEach(l=>{const o=document.createElement('option');o.value=l;o.textContent=l;ls.appendChild(o)});ls.value=len;const key=ti+'|'+p.currentPattern+'|'+len;const g=$('stepGrid');if(gridCache.key!==key){g.style.gridTemplateColumns='repeat('+len+',1fr)';g.innerHTML='';gridCache={key,cells:[],len};for(let i=0;i<len;i++){const c=document.createElement('div');c.className='cell'+(p.tracks[ti].kind!=='drum'?' syn':'')+(i%4===0?' beat':'');c.onclick=(idx=>ev=>{if(ev.shiftKey)stepEditor(ti,idx);else{pushHist();const st2=d.steps[idx];st2.on^=1;if(st2.on&&p.tracks[ti].kind!=='drum'&&st2.note<12)st2.note=p.root+24;updateCell(c,st2);I.dirty=true}})(i);g.appendChild(c);gridCache.cells.push(c)}}for(let i=0;i<len;i++)updateCell(gridCache.cells[i],d.steps[i])}
function updateCell(c,st){c.classList.toggle('on',!!st.on);c.style.opacity=st.on?(0.45+st.vel*0.55):1;c.classList.toggle('lock',Object.keys(st.lock).length>0)}
function stepEditor(ti,i){const pat=I.p.patterns[I.p.currentPattern],st=pat.data[ti].steps[i];const v=prompt('Step '+(i+1)+' — vel(0-1) prob(0-1) micro(-100..100)',st.vel+' '+st.prob+' '+st.micro);if(v){const parts=v.split(/\s+/);pushHist();if(parts[0]!=null&&!isNaN(+parts[0]))st.vel=clamp(+parts[0],0.05,1);if(parts[1]!=null&&!isNaN(+parts[1]))st.prob=clamp(+parts[1],0,1);if(parts[2]!=null&&!isNaN(+parts[2]))st.micro=clamp(+parts[2],-100,100)}const lv=prompt('Parameter lock cutoff (empty=none)',st.lock.cutoff!=null?st.lock.cutoff:'');if(lv!=null){pushHist();if(lv==='')delete st.lock.cutoff;else st.lock.cutoff=clamp(+lv,60,14000)}I.renderDirty=true}

function wireSeq(){$('seqTrack').onchange=e=>{I.selTrack=+e.target.value;I.renderDirty=true};$('lenSel').onchange=e=>{const ti=I.selTrack;const d=I.p.patterns[I.p.currentPattern].data[ti];pushHist();const l=+e.target.value;const old=d.steps;d.len=l;d.steps=Array.from({length:l},(_,k)=>old[k%old.length]||mkStep(false));after()};$('bClr').onclick=()=>{const ti=I.selTrack;pushHist();const d=I.p.patterns[I.p.currentPattern].data[ti];d.steps.forEach(s=>{s.on=0;s.lock={}});I.renderDirty=true};$('bDup').onclick=()=>{pushHist();const src=I.p.patterns[I.p.currentPattern];const np=deep(src);np.name=src.name+'2';I.p.patterns[np.name]=np;I.renderDirty=true};}

export { renderSeq, renderPos, wireSeq };
