import { $, I, pushHist, toast, after } from '../state.js';
import { deep } from '../model.js';
import { libFind, libFilter, libCount, assignPresetToTrack } from '../presets.js';

function renderLib(){const cat=$('libCat').value,genre=$('libGenre').value;const list=libFilter(cat,genre);$('libMeta').textContent='category '+cat.toUpperCase()+' · '+list.length+' presets · total factory '+libCount();const w=$('libList');w.innerHTML='';list.forEach(pr=>{const d=document.createElement('div');const assigned=I.p.tracks.some(t=>t.presetId===pr.id);d.className='lib'+(assigned?' assigned':'')+(I.selLib===pr.id?' assigned':'');d.innerHTML='<div><div class="ln">'+pr.name+'</div><div class="lm">'+pr.genre+' · '+pr.engine+'</div></div><div class="lm">'+pr.id+'</div>';d.onclick=()=>{I.selLib=pr.id;renderLib()};w.appendChild(d)})}
function renderSynthEd(){const t=I.p.tracks[I.selTrack];const w=$('synthEd');w.innerHTML='';if(t.kind!=='synth'){w.innerHTML='<div class="note">Drum track — synth editor N/A.</div>';return}const fields=[['cutoff','Cutoff',60,14000],['res','Reso x100',1,220],['atk','Attack ms',1,1500],['dec','Decay ms',1,2000],['sus','Sustain x100',0,100],['rel','Release ms',1,2500],['gate','Gate x100',5,300]];fields.forEach(([f,lb,mn,mx])=>{const d=document.createElement('div');const val=t.sound[f]!=null?t.sound[f]:(f==='cutoff'?1500:f==='res'?3:0);let disp=Math.round(val);if(['atk','dec','rel'].includes(f))disp=Math.round(val*1000);if(['sus','gate'].includes(f))disp=Math.round(val*100);d.innerHTML='<label>'+lb+'</label><input type="range" min="'+mn+'" max="'+mx+'" value="'+disp+'">';d.querySelector('input').oninput=e=>{let v=+e.target.value;if(['sus','gate'].includes(f))v/=100;if(['atk','dec','rel'].includes(f))v/=1000;t.sound[f]=v;I.dirty=true};w.appendChild(d)});['wave1','wave2'].forEach(f=>{const d=document.createElement('div');d.innerHTML='<label>'+f.toUpperCase()+'</label><select>'+['sawtooth','square','triangle','sine'].map(w=>'<option'+(w===t.sound[f]?' selected':'')+'>'+w+'</option>').join('')+'</select>';d.querySelector('select').onchange=e=>{t.sound[f]=e.target.value;I.dirty=true};w.appendChild(d)})}

function wireSound(){$('libCat').innerHTML=['all','drum','bass','lead','pad','pluck','arp','fx','synth'].map(c=>'<option>'+c+'</option>').join('');$('libGenre').innerHTML=['ALL','TECHNO','PSYTRANCE','TRANCE','PROGRESSIVE','ANY'].map(g=>'<option>'+g+'</option>').join('');$('libCat').onchange=renderLib;$('libGenre').onchange=renderLib;$('bAud').onclick=()=>{if(!I.selLib)return toast('select a preset');const pr=libFind(I.selLib);if(!pr)return;if(pr.cat==='drum'){const tr={idx:0,kind:'drum',sound:pr,type:pr.type};I.eng.trigger(tr,I.ctx.currentTime,{vel:.9,note:48,lock:{}},0)}else{const tr={idx:I.selTrack,kind:'synth',sound:pr};I.eng.trigger(tr,I.ctx.currentTime,{vel:.9,note:I.p.root+24,lock:{}},0)}};$('bAssign').onclick=()=>{if(!I.selLib)return toast('select a preset');const pr=libFind(I.selLib);if(!pr)return;pushHist();assignPresetToTrack(I.p,I.selTrack,pr);I.p.tracks[I.selTrack].base=deep({sound:I.p.tracks[I.selTrack].sound,mix:{sendA:I.p.tracks[I.selTrack].mix.sendA,sendB:I.p.tracks[I.selTrack].mix.sendB,vol:I.p.tracks[I.selTrack].mix.vol}});after();toast('assigned '+pr.id)};}

export { renderLib, renderSynthEd, wireSound };
