import { $, I, pushHist, toast, after } from '../state.js';
import { deep } from '../model.js';
import { libFind, libFilter, libCount, assignPresetToTrack } from '../presets.js';
import { autoRecMove } from '../state.js';
import { SOUND_IDS, paramApply, ensureIns } from '../params.js';
import { ensureVoice } from '../samplestore.js';
import { freezeTrack } from '../bounce.js';
import { importChannelsAsSample } from './samples.js';

function renderLib(){const cat=$('libCat').value,genre=$('libGenre').value;const list=libFilter(cat,genre);$('libMeta').textContent='category '+cat.toUpperCase()+' · '+list.length+' presets · total factory '+libCount();const w=$('libList');w.innerHTML='';list.forEach(pr=>{const d=document.createElement('div');const assigned=I.p.tracks.some(t=>t.presetId===pr.id);d.className='lib'+(assigned?' assigned':'')+(I.selLib===pr.id?' assigned':'');d.innerHTML='<div><div class="ln">'+pr.name+'</div><div class="lm">'+pr.genre+' · '+pr.engine+'</div></div><div class="lm">'+pr.id+'</div>';d.onclick=()=>{I.selLib=pr.id;renderLib()};w.appendChild(d)})}
function renderSynthEd(){const t=I.p.tracks[I.selTrack];const w=$('synthEd');w.innerHTML='';ensureVoice(t);
/* v0.10.0 VOICE row — every track: synth (default) or user-sample playback */
const vd=document.createElement('div');vd.style.gridColumn='1/-1';vd.innerHTML='<label>VOICE</label><select id="voiceModeSel"><option value="synth"'+(t.voiceMode==='sample'?'':' selected')+'>SYNTH</option><option value="sample"'+(t.voiceMode==='sample'?' selected':'')+'>SAMPLE</option></select> <select id="smpSel" style="max-width:170px;font-size:10px"></select><div class="mono" id="smpMetaEd" style="font-size:8px;color:var(--dim);grid-column:1/-1">'+(t.sampleMeta?('▲ '+t.sampleMeta.name+' · '+t.sampleMeta.durationSec.toFixed(2)+'s · pk '+t.sampleMeta.peak.toFixed(2)):'no sample assigned — the synth voice plays')+'</div>';w.appendChild(vd);vd.querySelector('#voiceModeSel').onchange=e=>{pushHist();t.voiceMode=e.target.value;I.dirty=true;I.renderDirty=true;if(e.target.value==='sample'&&!t.sampleId)toast('assign a sample below — until then the synth voice plays')};const smpSel=vd.querySelector('#smpSel');
if(I.sampleStore){I.sampleStore.list().then(rows=>{if(!document.body.contains(smpSel))return;smpSel.innerHTML='<option value="">— assign sample —</option>'+rows.map(r=>'<option value="'+r.id+'"'+(t.sampleId===r.id?' selected':'')+'>'+r.name+' ('+r.durationSec.toFixed(2)+'s)</option>').join('');smpSel.onchange=e=>{pushHist();const r=rows.find(x=>x.id===e.target.value);t.sampleId=r?r.id:null;t.sampleMeta=r?{name:r.name,durationSec:r.durationSec,peak:r.peak}:null;if(r){t.voiceMode='sample'/* assigning a sample means wanting to hear it */;if(I.eng&&!I.eng.hasSampleBuffer(r.id))I.eng.loadSampleBuffer(r)}if(I.missingSampleIds)I.missingSampleIds.length=0;I.dirty=true;I.renderDirty=true;const meta=vd.querySelector('#smpMetaEd');if(meta)meta.textContent=r?('▲ '+r.name+' · '+r.durationSec.toFixed(2)+'s · pk '+r.peak.toFixed(2)+' · '+r.sampleRate+'Hz'):'no sample assigned — the synth voice plays';if(r)toast('SAMPLE → '+(t.name||('track-'+I.selTrack))+' ✓ '+r.name+' — voice switched to SAMPLE')}})}
/* v0.11.0 FREEZE — render THIS track's current pattern loop into the sample
   store (inserts baked, sends/sidechain excluded — POST-insert PRE-send).
   The frozen sample is NOT auto-assigned back to its own track (that would
   flip the just-frozen track's voice mid-edit — surprising); assign via the
   VOICE select or select a target track before a RESAMPLE. */
{const fb=document.createElement('button');fb.id='bFreeze';fb.textContent='FREEZE';fb.title='Render this track for one pattern loop into the sample store — inserts baked, sends and sidechain excluded (POST-insert PRE-send)';fb.style.cssText='font-size:9px;padding:2px 6px';vd.appendChild(fb);fb.onclick=async()=>{if(I.engine==='worklet'){toast('FREEZE: unsupported on the WORKLET engine (reduced feature set)');return}if(!I.eng||!I.ctx){toast('POWER ON first');return}if(I.selTrack==null||!I.p)return;fb.disabled=true;const old=fb.textContent;fb.textContent='FREEZE…';toast('FREEZING '+(t.name||('track-'+I.selTrack))+' — one pattern loop…');try{const r=await freezeTrack(I.p,I.selTrack,{samples:I.eng.sampleCache||null});if(r.error){toast('FREEZE REFUSED — '+r.error);return}const slug=String(t.name||('track-'+I.selTrack)).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'track';const rec=await importChannelsAsSample('freeze-'+slug,r.channels,r.sampleRate,false);if(rec)toast('FREEZE ✓ '+rec.name+' · '+rec.durationSec.toFixed(2)+'s — assign via VOICE ▸ sample select')}catch(e){toast('FREEZE FAILED — '+(e&&e.message||e))}finally{fb.disabled=false;fb.textContent=old}}}
/* v0.10.0 INSERT row — drive / crush / filter, pre-send, all registry params */
{const ins=ensureIns(t).ins;const idv=document.createElement('div');idv.style.gridColumn='1/-1';idv.innerHTML='<label>INS</label><div style="display:flex;gap:4px;align-items:center;flex-wrap:wrap;grid-column:1/-1"><span class="mono" style="font-size:8px;color:var(--dim)">DRV</span><input type="range" id="insDriveR" min="0" max="100" value="'+ins.drive+'" title="drive — input trim into the fixed soft-clip; 0 = exact dry path"><span class="mono" style="font-size:8px;color:var(--dim)">CRSH</span><input type="range" id="insCrushR" min="2" max="16" value="'+ins.crush+'" title="bit crush — 16 = bypass"><select id="insFiltSel" title="insert filter mode">'+['OFF','LP','HP','BP'].map((m,i)=>'<option value="'+i+'"'+(+ins.filtOn===i?' selected':'')+'>'+m+'</option>').join('')+'</select><span class="mono" style="font-size:8px;color:var(--dim)">FREQ</span><input type="range" id="insFiltFreqR" min="20" max="20000" value="'+Math.round(ins.filtFreq)+'" title="cutoff Hz (log-scale feel — drag)"><span class="mono" style="font-size:8px;color:var(--dim)">Q</span><input type="range" id="insFiltQR" min="1" max="180" value="'+Math.round(ins.filtQ*10)+'" title="resonance Q x10"></div>';w.appendChild(idv);const insMove=(id,v)=>{paramApply(t,id,v);I.dirty=true;autoRecMove(I.selTrack,id,v);after()};idv.querySelector('#insDriveR').oninput=e=>insMove('insDrive',+e.target.value);idv.querySelector('#insCrushR').oninput=e=>insMove('insCrush',+e.target.value);idv.querySelector('#insFiltSel').onchange=e=>insMove('insFiltOn',+e.target.value);idv.querySelector('#insFiltFreqR').oninput=e=>insMove('insFiltFreq',+e.target.value);idv.querySelector('#insFiltQR').oninput=e=>insMove('insFiltQ',+e.target.value/10)}
if(t.voiceMode==='sample'){const sp=t.sampleParams;const ids=['smpGain','smpTune','smpStart','smpEnd','smpRev','smpAtk','smpRel','smpSlice'];[['gain','Gain x100',0,200],['tune','Tune semitones',-24,24],['startPct','Start %',0,100],['endPct','End %',0,100],['reverse','Reverse',0,1],['attackMs','Attack ms',0,100],['releaseMs','Release ms',0,500],['sliceIdx','Slice idx (0=full)',0,16]].forEach(([f,lb,mn,mx],i)=>{const d=document.createElement('div');d.innerHTML='<label>'+lb+'</label><input type="range" min="'+mn+'" max="'+mx+'" value="'+Math.round(sp[f]*(f==='gain'?100:1))+'">';d.querySelector('input').oninput=e=>{let v=+e.target.value;if(f==='gain')v/=100;if(f==='reverse')sp[f]=v>=0.5?1:0;else sp[f]=v;I.dirty=true;autoRecMove(I.selTrack,ids[i],sp[f])};w.appendChild(d)});return}
if(t.kind!=='synth'){const n=document.createElement('div');n.style.gridColumn='1/-1';n.className='note';n.textContent='Drum track — synth editor N/A (switch VOICE to SAMPLE to play a user sample).';w.appendChild(n);return}const fields=[['cutoff','Cutoff',60,14000],['res','Reso x100',1,220],['atk','Attack ms',1,1500],['dec','Decay ms',1,2000],['sus','Sustain x100',0,100],['rel','Release ms',1,2500],['gate','Gate x100',5,300]];fields.forEach(([f,lb,mn,mx])=>{const d=document.createElement('div');const val=t.sound[f]!=null?t.sound[f]:(f==='cutoff'?1500:f==='res'?3:0);let disp=Math.round(val);if(['atk','dec','rel'].includes(f))disp=Math.round(val*1000);if(['sus','gate'].includes(f))disp=Math.round(val*100);d.innerHTML='<label>'+lb+'</label><input type="range" min="'+mn+'" max="'+mx+'" value="'+disp+'">';d.querySelector('input').oninput=e=>{let v=+e.target.value;if(['sus','gate'].includes(f))v/=100;if(['atk','dec','rel'].includes(f))v/=1000;t.sound[f]=v;I.dirty=true;if(SOUND_IDS.has(f))autoRecMove(I.selTrack,f,v)};w.appendChild(d)});['wave1','wave2'].forEach(f=>{const d=document.createElement('div');d.innerHTML='<label>'+f.toUpperCase()+'</label><select>'+['sawtooth','square','triangle','sine'].map(w=>'<option'+(w===t.sound[f]?' selected':'')+'>'+w+'</option>').join('')+'</select>';d.querySelector('select').onchange=e=>{t.sound[f]=e.target.value;I.dirty=true};w.appendChild(d)})}

function wireSound(){$('libCat').innerHTML=['all','drum','bass','lead','pad','pluck','arp','fx','synth'].map(c=>'<option>'+c+'</option>').join('');$('libGenre').innerHTML=['ALL','TECHNO','PSYTRANCE','TRANCE','PROGRESSIVE','ANY'].map(g=>'<option>'+g+'</option>').join('');$('libCat').onchange=renderLib;$('libGenre').onchange=renderLib;$('bAud').onclick=()=>{if(!I.selLib)return toast('select a preset');const pr=libFind(I.selLib);if(!pr)return;if(pr.cat==='drum'){const tr={idx:0,kind:'drum',sound:pr,type:pr.type};I.eng.trigger(tr,I.ctx.currentTime,{vel:.9,note:48,lock:{}},0)}else{const tr={idx:I.selTrack,kind:'synth',sound:pr};I.eng.trigger(tr,I.ctx.currentTime,{vel:.9,note:I.p.root+24,lock:{}},0)}};$('bAssign').onclick=()=>{if(!I.selLib)return toast('select a preset');const pr=libFind(I.selLib);if(!pr)return;pushHist();assignPresetToTrack(I.p,I.selTrack,pr);I.p.tracks[I.selTrack].base=deep({sound:I.p.tracks[I.selTrack].sound,mix:{sendA:I.p.tracks[I.selTrack].mix.sendA,sendB:I.p.tracks[I.selTrack].mix.sendB,vol:I.p.tracks[I.selTrack].mix.vol}});after();toast('assigned '+pr.id)};}

export { renderLib, renderSynthEd, wireSound };
