import { $, I, pushHist, toast, after, saveProject } from '../state.js';
import { deep } from '../model.js';
import { libFind, libFilter, libCount, assignPresetToTrack } from '../presets.js';
import { autoRecMove } from '../state.js';
import { SOUND_IDS, paramApply, ensureIns } from '../params.js';
import { ensureVoice } from '../samplestore.js';
import { freezeTrack } from '../bounce.js';
import { importChannelsAsSample } from './samples.js';
import { KIT_IDS, DEFAULT_KIT, STYLE_KIT, kitMeta, kitWarmTypes } from '../../foundation/dsp/kit-reason.mjs';

/* v0.16.1 PERF — sig-gated preset list: the 345-row rebuild only happens when the filter/query/selection/assignment actually changed.
   v0.26.0 ROAST FIX #7 — the list is built through a DocumentFragment and clicks are DELEGATED to the container (456 individual onclick closures are gone); the search input is debounced 120 ms so typing no longer rebuilds the list per keystroke. */
let libSig='';
function renderLib(){const cat=$('libCat').value,genre=$('libGenre').value;const q=(($('libQ')&&$('libQ').value)||'').trim().toLowerCase();const list=libFilter(cat,genre).filter(pr=>!q||(pr.name+' '+pr.id+' '+pr.genre).toLowerCase().includes(q));const meta='category '+cat.toUpperCase()+' · '+list.length+' presets · total factory '+libCount()+(q?' · q "'+q+'"':'');$('libMeta').textContent=meta;const assignedKey=I.p.tracks.map(t=>t.presetId||'').join(',');const sig=cat+'#'+genre+'#'+q+'#'+I.selLib+'#'+assignedKey+'#'+list.length;if(sig===libSig&&$('libList').children.length===list.length)return;libSig=sig;const w=$('libList');w.innerHTML='';const frag=document.createDocumentFragment();list.forEach(pr=>{const d=document.createElement('div');const assigned=I.p.tracks.some(t=>t.presetId===pr.id);d.className='lib'+(assigned?' assigned':'')+(I.selLib===pr.id?' assigned':'');d.dataset.pid=pr.id;d.innerHTML='<div><div class="ln">'+pr.name+'</div><div class="lm">'+pr.genre+' · '+pr.engine+'</div></div><div class="lm">'+pr.id+'</div>';frag.appendChild(d)});w.appendChild(frag)}
function renderSynthEd(){const t=I.p.tracks[I.selTrack];const w=$('synthEd');w.innerHTML='';ensureVoice(t);
/* v0.10.0 VOICE row — every track: synth (default) or user-sample playback */
const vd=document.createElement('div');vd.style.gridColumn='1/-1';vd.innerHTML='<label for="voiceModeSel">VOICE</label><select id="voiceModeSel"><option value="synth"'+(t.voiceMode==='sample'?'':' selected')+'>SYNTH</option><option value="sample"'+(t.voiceMode==='sample'?' selected':'')+'>SAMPLE</option></select> <select id="smpSel" aria-label="user sample" style="max-width:170px;font-size:10px"></select><div class="mono" id="smpMetaEd" style="font-size:8px;color:var(--dim);grid-column:1/-1">'+(t.sampleMeta?('▲ '+t.sampleMeta.name+' · '+t.sampleMeta.durationSec.toFixed(2)+'s · pk '+t.sampleMeta.peak.toFixed(2)):'no sample assigned — the synth voice plays')+'</div>';w.appendChild(vd);vd.querySelector('#voiceModeSel').onchange=e=>{pushHist();t.voiceMode=e.target.value;I.dirty=true;I.renderDirty=true;if(e.target.value==='sample'&&!t.sampleId)toast('assign a sample below — until then the synth voice plays')};const smpSel=vd.querySelector('#smpSel');
if(I.sampleStore){I.sampleStore.list().then(rows=>{if(!document.body.contains(smpSel))return;smpSel.innerHTML='<option value="">— assign sample —</option>'+rows.map(r=>'<option value="'+r.id+'"'+(t.sampleId===r.id?' selected':'')+'>'+r.name+' ('+r.durationSec.toFixed(2)+'s)</option>').join('');smpSel.onchange=e=>{pushHist();const r=rows.find(x=>x.id===e.target.value);t.sampleId=r?r.id:null;t.sampleMeta=r?{name:r.name,durationSec:r.durationSec,peak:r.peak}:null;if(r){t.voiceMode='sample'/* assigning a sample means wanting to hear it */;if(I.eng&&!I.eng.hasSampleBuffer(r.id))I.eng.loadSampleBuffer(r)}if(I.missingSampleIds)I.missingSampleIds.length=0;I.dirty=true;I.renderDirty=true;const meta=vd.querySelector('#smpMetaEd');if(meta)meta.textContent=r?('▲ '+r.name+' · '+r.durationSec.toFixed(2)+'s · pk '+r.peak.toFixed(2)+' · '+r.sampleRate+'Hz'):'no sample assigned — the synth voice plays';if(r)toast('SAMPLE → '+(t.name||('track-'+I.selTrack))+' ✓ '+r.name+' — voice switched to SAMPLE')}})}
/* v0.11.0 FREEZE — render THIS track's current pattern loop into the sample
   store (inserts baked, sends/sidechain excluded — POST-insert PRE-send).
   The frozen sample is NOT auto-assigned back to its own track (that would
   flip the just-frozen track's voice mid-edit — surprising); assign via the
   VOICE select or select a target track before a RESAMPLE. */
{const fb=document.createElement('button');fb.id='bFreeze';fb.textContent='FREEZE';fb.title='Render this track for one pattern loop into the sample store — inserts baked, sends and sidechain excluded (POST-insert PRE-send)';fb.style.cssText='font-size:9px;padding:2px 6px';vd.appendChild(fb);fb.onclick=async()=>{if(I.engine==='worklet'){toast('FREEZE: unsupported on the WORKLET engine (reduced feature set)');return}if(!I.eng||!I.ctx){toast('POWER ON first');return}if(I.selTrack==null||!I.p)return;fb.disabled=true;const old=fb.textContent;fb.textContent='FREEZE…';toast('FREEZING '+(t.name||('track-'+I.selTrack))+' — one pattern loop…');try{const r=await freezeTrack(I.p,I.selTrack,{samples:I.eng.sampleCache||null});if(r.error){toast('FREEZE REFUSED — '+r.error);return}const slug=String(t.name||('track-'+I.selTrack)).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'track';const rec=await importChannelsAsSample('freeze-'+slug,r.channels,r.sampleRate,false);if(rec)toast('FREEZE ✓ '+rec.name+' · '+rec.durationSec.toFixed(2)+'s — assign via VOICE ▸ sample select')}catch(e){toast('FREEZE FAILED — '+(e&&e.message||e))}finally{fb.disabled=false;fb.textContent=old}}}
/* v0.10.0 INSERT row — drive / crush / filter, pre-send, all registry params */
{const ins=ensureIns(t).ins;const idv=document.createElement('div');idv.style.gridColumn='1/-1';idv.innerHTML='<span class="mono" style="font-size:8px;color:var(--dim);grid-column:1/-1">INS — pre-send insert chain</span><div style="display:flex;gap:4px;align-items:center;flex-wrap:wrap;grid-column:1/-1"><span class="mono" style="font-size:8px;color:var(--dim)">DRV</span><input type="range" id="insDriveR" min="0" max="100" value="'+ins.drive+'" title="drive — input trim into the fixed soft-clip; 0 = exact dry path"><span class="mono" style="font-size:8px;color:var(--dim)">CRSH</span><input type="range" id="insCrushR" min="2" max="16" value="'+ins.crush+'" title="bit crush — 16 = bypass"><select id="insFiltSel" aria-label="insert filter type" title="insert filter mode - MOOG = psy-dsp ladder (AudioWorklet; offline renders prep it; unloadable -> counted biquad LP fallback)">'+['OFF','LP','HP','BP','MOOG'].map((m,i)=>'<option value="'+i+'"'+(+ins.filtOn===i?' selected':'')+'>'+m+'</option>').join('')+'</select><span class="mono" style="font-size:8px;color:var(--dim)">FREQ</span><input type="range" id="insFiltFreqR" min="20" max="20000" value="'+Math.round(ins.filtFreq)+'" title="cutoff Hz (log-scale feel — drag)"><span class="mono" style="font-size:8px;color:var(--dim)">Q</span><input type="range" id="insFiltQR" min="1" max="180" value="'+Math.round(ins.filtQ*10)+'" title="resonance Q x10"></div>';w.appendChild(idv);const insMove=(id,v)=>{paramApply(t,id,v);I.dirty=true;autoRecMove(I.selTrack,id,v);after()};idv.querySelector('#insDriveR').oninput=e=>insMove('insDrive',+e.target.value);idv.querySelector('#insCrushR').oninput=e=>insMove('insCrush',+e.target.value);idv.querySelector('#insFiltSel').onchange=e=>insMove('insFiltOn',+e.target.value);idv.querySelector('#insFiltFreqR').oninput=e=>insMove('insFiltFreq',+e.target.value);idv.querySelector('#insFiltQR').oninput=e=>insMove('insFiltQ',+e.target.value/10)}
if(t.voiceMode==='sample'){const sp=t.sampleParams;const ids=['smpGain','smpTune','smpStart','smpEnd','smpRev','smpAtk','smpRel','smpSlice'];[['gain','Gain x100',0,200],['tune','Tune semitones',-24,24],['startPct','Start %',0,100],['endPct','End %',0,100],['reverse','Reverse',0,1],['attackMs','Attack ms',0,100],['releaseMs','Release ms',0,500],['sliceIdx','Slice idx (0=full)',0,16]].forEach(([f,lb,mn,mx],i)=>{const d=document.createElement('div');d.innerHTML='<label for="sp_'+i+'">'+lb+'</label><input id="sp_'+i+'" type="range" min="'+mn+'" max="'+mx+'" value="'+Math.round(sp[f]*(f==='gain'?100:1))+'">';d.querySelector('input').oninput=e=>{let v=+e.target.value;if(f==='gain')v/=100;if(f==='reverse')sp[f]=v>=0.5?1:0;else sp[f]=v;I.dirty=true;autoRecMove(I.selTrack,ids[i],sp[f])};w.appendChild(d)});return}
if(t.kind!=='synth'){
/* v0.14.0 P2: DRUM TRACK EDITOR — the dead-end note is gone. Every drum
   track now exposes a TYPE select (all 21 engine types) + the 4 core drum
   params (tune/decay/tone/punch) + the 4 optional v0.14.0 params
   (dist/glide/bursts/bright — written on first move, absence stays
   legacy-neutral). Assigning a preset still works exactly as before. */
const t0=t.sound.type||t.type||'kick';
const dd=document.createElement('div');dd.style.gridColumn='1/-1';
const TYPES=['kick','snare','clap','hatC','hatO','tom','rim','conga','bongo','cowbell','clave','zap','boom','glitch','shaker','riser','impact','darbuka','tambourine','triangle','downlifter'];
dd.innerHTML='<label for="drTypeSel">TYPE</label><select id="drTypeSel" title="drum synthesis type — the engine voice model for this track">'+TYPES.map(x=>'<option'+(x===t0?' selected':'')+'>'+x+'</option>').join('')+'</select>';
w.appendChild(dd);
dd.querySelector('#drTypeSel').onchange=e=>{pushHist();t.sound.type=e.target.value;t.type=e.target.value;I.dirty=true;I.renderDirty=true;toast('TYPE → '+e.target.value)};
const dparams=[['tune','TUNE x100',30,200,100],['decay','DECAY x100',10,400,100],['tone','TONE x100',30,250,100],['punch','PUNCH x100',0,100,0]];
const dv2=[['dist','DIST x100 (kick)',0,100,0],['glide','GLIDE x100 (kick)',0,100,0],['bursts','BURSTS (clap)',2,6,4],['bright','BRIGHT x100 (hat)',50,200,100]];
[...dparams,...dv2].forEach(([f,lb,mn,mx,df],i)=>{
const cur=t.sound[f]!=null?t.sound[f]:null;
const val=cur!=null?Math.round(cur*(f==='bursts'?1:100)):df;
const d2=document.createElement('div');
d2.innerHTML='<label for="dr_'+i+'">'+lb+'</label><input id="dr_'+i+'" type="range" min="'+mn+'" max="'+mx+'" value="'+val+'" title="'+(dv2.some(v=>v[0]===f)?'v0.14.0 optional param — default = exact v0.13.1 sound':'core drum param')+'">';
d2.querySelector('input').oninput=e=>{let v=+e.target.value;if(f!=='bursts')v/=100;t.sound[f]=v;I.dirty=true};
w.appendChild(d2)});
return}const fields=[['cutoff','Cutoff',60,14000],['res','Reso x100',1,220],['atk','Attack ms',1,1500],['dec','Decay ms',1,2000],['sus','Sustain x100',0,100],['rel','Release ms',1,2500],['gate','Gate x100',5,300]];fields.forEach(([f,lb,mn,mx])=>{const d=document.createElement('div');const val=t.sound[f]!=null?t.sound[f]:(f==='cutoff'?1500:f==='res'?3:0);let disp=Math.round(val);if(['atk','dec','rel'].includes(f))disp=Math.round(val*1000);if(['sus','gate'].includes(f))disp=Math.round(val*100);d.innerHTML='<label for="sy_'+f+'">'+lb+'</label><input id="sy_'+f+'" type="range" min="'+mn+'" max="'+mx+'" value="'+disp+'">';d.querySelector('input').oninput=e=>{let v=+e.target.value;if(['sus','gate'].includes(f))v/=100;if(['atk','dec','rel'].includes(f))v/=1000;t.sound[f]=v;I.dirty=true;if(SOUND_IDS.has(f))autoRecMove(I.selTrack,f,v)};w.appendChild(d)});/* v0.13.0 SYNTH v2-lite — the five optional engine params, editable in the Sound tab. Every one legacy-neutral (absent ⇒ v0.12.0 sound). */

 [['fenv','FEnv x1',0,16],['penv','PitchEnv st',0,48],['sub','Sub x100',0,100],['fdec2','FDec ms',10,2000],['pdec2','PDec ms',10,600]].forEach(([f,lb,mn,mx])=>{const d=document.createElement('div');const src=f==='fdec2'?'fdec':f==='pdec2'?'pdec':f==='sub'?'sub':f;const val=t.sound[src]!=null?t.sound[src]:(src==='fenv'?3:0);let disp=Math.round(val);if(src==='sub')disp=Math.round(val*100);if(src==='fdec'||src==='pdec')disp=Math.round(val*1000);d.innerHTML='<label for="v2_'+f+'">'+lb+'</label><input id="v2_'+f+'" type="range" min="'+mn+'" max="'+mx+'" value="'+disp+'" title="v0.13.0 synth param — default = legacy v0.12.0 behavior">';d.querySelector('input').oninput=e=>{let v=+e.target.value;if(src==='sub')v/=100;if(src==='fdec'||src==='pdec')v/=1000;t.sound[src]=v;I.dirty=true};w.appendChild(d)});['wave1','wave2'].forEach(f=>{const d=document.createElement('div');d.innerHTML='<label for="wv_'+f+'">'+f.toUpperCase()+'</label><select id="wv_'+f+'">'+['sawtooth','square','triangle','sine'].map(w=>'<option'+(w===t.sound[f]?' selected':'')+'>'+w+'</option>').join('')+'</select>';d.querySelector('select').onchange=e=>{t.sound[f]=e.target.value;I.dirty=true};w.appendChild(d)})}

/* v0.24.0 KIT SELECTOR — the whole drum kit follows the REASON kit system.
   'auto' = follow the project style (STYLE_KIT); an explicit kit = PINNED
   (survives save/load + compose until unpinned). Both paths call
   eng.setKit + re-warm the new kit's 20 buffers (idle-sliced — never the
   hot path) and save the snapshot. syncKitSel mirrors state → select (no
   DOM write unless the value drifted) and is called from renderAll. */
let _kitWarmStop=false;
function warmKit(kit){if(!I.eng||!I.eng.romBuffer)return;const list=kitWarmTypes(kit);let wi=0;const step=()=>{if(_kitWarmStop)return;const dl=(window.requestIdleCallback||(cb=>setTimeout(cb,16)));dl(()=>{try{if(!I.eng)return;if(wi<list.length){I.eng.romBuffer(list[wi++]);step()}}catch(e){}})};step()}
function syncKitSel(){const s=$('kitSel'),p=I.p;if(!s||!p)return;const v=(p.kitPinned&&kitMeta(p.kit))?p.kit:'auto';if(s.value!==v)s.value=v}
function wireKitSel(){const row=$('libCat')&&$('libCat').parentElement;if(!row||$('kitSel'))return;const s=document.createElement('select');s.id='kitSel';s.setAttribute('aria-label','drum kit');s.title='the drum KIT — every kit is one instrument (all voices tuned to the kit root, leveled to the family loudness law). auto = follow the project style; an explicit kit is PINNED (persists through save/load and compose)';s.innerHTML='<option value="auto">KIT auto (follow style)</option>'+KIT_IDS.map(id=>{const m=kitMeta(id);return '<option value="'+id+'">'+(m?m.name:id)+'</option>'}).join('');row.appendChild(s);
s.onchange=()=>{const p=I.p;if(!p)return;pushHist();_kitWarmStop=true;_kitWarmStop=false;if(s.value==='auto'){p.kitPinned=false;p.kit=STYLE_KIT[String(p.style||'').toLowerCase()]||DEFAULT_KIT}else{p.kitPinned=true;p.kit=s.value}
if(I.eng&&I.eng.setKit){I.eng.setKit(p.kit);warmKit(p.kit)}I.dirty=true;syncKitSel();saveProject();const m=kitMeta(p.kit);toast('KIT → '+(m?m.name:p.kit)+(p.kitPinned?' (pinned)':' (follows style)'))}}

function wireSound(){$('libCat').innerHTML=['all','drum','bass','lead','pad','pluck','arp','fx','synth','texture'].map(c=>'<option>'+c+'</option>').join('');/* v0.19.0 FIX: the genre list was HARDCODED and had drifted — FOREST (a first-class genre since its own voices shipped) was unfilterable. Derived from the library itself now: every genre that owns presets appears, and a future genre can never go missing again. */const gset=[...new Set(libFilter('all','ALL').map(x=>x.genre).filter(g=>g!=='ANY'))];$('libGenre').innerHTML=['ALL',...gset,'ANY'].map(g=>'<option>'+g+'</option>').join('');$('libCat').onchange=renderLib;$('libGenre').onchange=renderLib;if($('libQ')){/* v0.26.0: 120 ms trailing debounce — one rebuild per pause, not per keystroke */let libQT=null;$('libQ').oninput=()=>{clearTimeout(libQT);libQT=setTimeout(renderLib,120)}}/* v0.26.0: ONE delegated listener replaces the per-row onclick closures */$('libList').onclick=e=>{const row=e.target&&e.target.closest?e.target.closest('.lib'):null;if(!row||!row.dataset.pid)return;I.selLib=row.dataset.pid;renderLib()};wireKitSel();$('bAud').onclick=()=>{if(!I.selLib)return toast('select a preset');const pr=libFind(I.selLib);if(!pr)return;if(pr.cat==='drum'){const tr={idx:0,kind:'drum',sound:pr,type:pr.type};I.eng.trigger(tr,I.ctx.currentTime,{vel:.9,note:48,lock:{}},0)}else{const tr={idx:I.selTrack,kind:'synth',sound:pr};I.eng.trigger(tr,I.ctx.currentTime,{vel:.9,note:I.p.root+24,lock:{}},0)}};$('bAssign').onclick=()=>{if(!I.selLib)return toast('select a preset');const pr=libFind(I.selLib);if(!pr)return;pushHist();assignPresetToTrack(I.p,I.selTrack,pr);I.p.tracks[I.selTrack].base=deep({sound:I.p.tracks[I.selTrack].sound,mix:{sendA:I.p.tracks[I.selTrack].mix.sendA,sendB:I.p.tracks[I.selTrack].mix.sendB,vol:I.p.tracks[I.selTrack].mix.vol}});after();toast('assigned '+pr.id)};}

export { renderLib, renderSynthEd, wireSound, syncKitSel };
